language: java
dist: trusty
jdk:
  - openjdk8
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.0.1-bin.zip
  - unzip -qq gradle-6.0.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.0.1
  - export PATH=$GRADLE_HOME/bin:$PATH
before_script: cd music-shop/
script:
  - gradle build
