version: '3.7'

services:
  restapp:
    build:
      context: ./
      dockerfile: Dockerfile.restapp
    container_name: restapp
    ports:
      - 8081:8081
    restart: always

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    container_name: webapp
    ports:
      - 8082:8082
    environment:
      RESTAPP_HOST: restapp
    depends_on:
      - restapp
    restart: always
