version: '3.3'

services:
  restapp:
    build:
      context: ./
      dockerfile: Dockerfile.restapp
    ports:
      - 8081:8081
    restart: always

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    ports:
      - 8082:8082
    depends_on:
      - restapp
    restart: always
