version: '3.7'

services:
  restapp:
    build:
      context: ./
      dockerfile: Dockerfile.restapp
    container_name: restapp
    ports:
      - 8083:8083
    restart: always

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    container_name: webapp
    ports:
      - 8084:8084
    environment:
      RESTAPP_HOST: restapp
    depends_on:
      - restapp
    restart: always
