FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR=/broomstick-shop-rest-app/build/libs/*.jar
COPY ${JAR} broomstick-shop-rest-app-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","broomstick-shop-rest-app-1.0-SNAPSHOT.jar"]